var gmail = require('../controllers/mailController');
var bcrypt = require('bcrypt');
var jwt = require('jsonwebtoken');
var express = require('express');
var router = express.Router();
var authenticated = require('../middleware/authenticatedUser');
require('dotenv').config();

var userModel = require('../models/userModel'); //Users collection
var expenseModel = require('../models/expenseModel'); //Expenses collection
var configurationModel = require('../models/configurationModel') //Configurations collection

// Send register page
router.get('/', authenticated, function (req, res) {
  res.render('register', { message: "" });
});

// Validate register page
router.post('/', authenticated, async function (req, res) {
  let username = req.body.username.toLowerCase();
  let email = req.body.email;
  let password = await bcrypt.hash(req.body.password, 10);

  if (await userModel.findOne({ username: username })) {
    res.render('register', { message: "Username already exists" });
  }
  else if (await userModel.findOne({ email: email })) {
    res.render('register', { message: "Email already exists" });
  }
  else {
    //Creating new user
    const newUser = {
      username: username,
      email: email,
      password: password
    };
    try {
      let result = await userModel.create(newUser);
      const token = jwt.sign({ username: username, email: email }, process.env.JWT_SECRET, { expiresIn: '24hrs' });
      res.cookie('token', token, { maxAge: 24 * 60 * 60 * 1000 });

      await configurationModel.create({ user: username });

      //Send mail
      let html = `
      <h1>Welcome to Expense Guard</h1>
      <p>Your account has been created successfully.</p>
      <br>
      <p>This is an autogenerated message. Please do not reply to this email.</p>
      <p>If you have any questions or concerns, feel free to reach out to our support team at help.expenseguard@gmail.com</p>
      `;
      gmail.sendMail(email, html, "Registration Successful");
      
      res.redirect('/dashboard');
    }
    catch (err) {
      console.error(err);
      res.render('register', { message: "Try again after sometime" });
    }
  }
});

module.exports = router;