var sendMail = require('../middleware/email');

const sendNotification = function (email, configuration, expenses) {
  const today = new Date();
  const notificationFrequency = configuration.notificationFrequency;
  const notificationTrack = configuration.notificationTrack ? new Date(configuration.notificationTrack) : undefined;

  if (notificationFrequency === 'daily') {
    // Check if notification was already sent today
    if (notificationTrack && isSameDate(today, notificationTrack)) {
      return;
    }
    // Send email notification if user prefers email
    if (configuration.notificationChannels.includes('email')) {
      sendMail(email, createNotificationContent(configuration, expenses));
    }
  }
  else if (notificationFrequency === 'weekly') {
    // Check if today is within the current week
    if (notificationTrack && isSameWeek(today, notificationTrack)) {
      return;
    }
    // Send email notification if user prefers email
    if (configuration.notificationChannels.includes('email')) {
      sendMail(email, createNotificationContent(configuration, expenses));
    }
  }
}


const createNotificationContent = function (configuration, expenses) {

  // Fetch the current date
  const today = new Date();

  // Fetch the current month from the date
  const selectedMonth = new Date().toISOString().slice(0, 7);

  // Fetch the monthly budget for the selected month from configuration
  const monthlyBudgetForMonth = configuration.monthlyBudget.find(entry => entry.year === parseInt(selectedMonth.split('-')[0]) && entry.month === parseInt(selectedMonth.split('-')[1]));
  const monthlyBudget = monthlyBudgetForMonth ? monthlyBudgetForMonth.budget : configuration.defaultMonthlyBudget;

  // Directly use the expenses array as all entries are for the selected month
  const dailyExpensesForMonth = expenses;

  // Calculate and display total spent, total budget, and remaining budget
  const totalSpentMonth = dailyExpensesForMonth.reduce((total, expense) => total + expense.amount, 0);

  // Calculate prediction rates
  const monthlyPredictionSpending = (totalSpentMonth / today.getDate()) * new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate();

  // Get the spent percentage
  const spentPercentage = (monthlyPredictionSpending / monthlyBudget) * 100;

  let htmlContent;

  if (spentPercentage <= 80) {
    htmlContent = `
      <h1> Spending Analysis </h1>
      <p style="font-size: 16px"> <b>Total Spent:</b> ${totalSpentMonth} </p>
      <p style="font-size: 16px"> <b>Budget Set:</b> ${monthlyBudget} </p>
      <p style="font-size: 16px"> <b>Predicted Spending:</b> ${monthlyPredictionSpending.toFixed(2)} </p>
      <p>Your spending is within a healthy range. Keep up the good work!</p>
    `;
  }
  else if (spentPercentage <= 95) {
    htmlContent = `
    <h1> Spending Analysis </h1>
    <p style="font-size: 16px"> <b>Total Spent:</b> ${totalSpentMonth} </p>
      <p style="font-size: 16px"> <b>Budget Set:</b> ${monthlyBudget} </p>
      <p style="font-size: 16px"> <b>Predicted Spending:</b> ${monthlyPredictionSpending.toFixed(2)} </p>
      <p>Your spending is approaching the budget limit. Consider reviewing your expenses.</p>
    `;
  }
  else {
    htmlContent = `
      <h1> Spending Analysis </h1>
      <p style="font-size: 16px"> <b>Total Spent:</b> ${totalSpentMonth} </p>
      <p style="font-size: 16px"> <b>Budget Set:</b> ${monthlyBudget} </p>
      <p style="font-size: 16px"> <b>Predicted Spending:</b> ${monthlyPredictionSpending.toFixed(2)} </p>
      <p>Your spending is exceeding the budget. It's essential to reassess and adjust your financial plan.</p>
    `;
  }

  const autogeneratedMessage = `
    <br>
    <p>This is an autogenerated message. Please do not reply to this email.</p>
    <p>If you have any questions or concerns, feel free to reach out to our support team at help.expenseguard@gmail.com</p>
  `;

  htmlContent += autogeneratedMessage;
  return htmlContent;
}

// Function to check if two dates are on the same day
function isSameDate(date1, date2) {
  return (
    date1.getFullYear() === date2.getFullYear() &&
    date1.getMonth() === date2.getMonth() &&
    date1.getDate() === date2.getDate()
  );
}

// Function to check if two dates are in the same week (Monday to Sunday)
function isSameWeek(date1, date2) {
  const oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
  const diffDays = Math.abs(Math.round((date2 - date1) / oneDay));

  return diffDays < 7;
}

module.exports = sendNotification;